
version: '2'

services:
  prometheus:
    image: khacnhat/prometheus-dojo
    build:
      context: .
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
    container_name: cyber-dojo-prometheus
    ports:
        - '9090:9090'
